version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      hdspark_net:
        ipv4_address: 11.0.2.51

    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    networks:
      hdspark_net:
        ipv4_address: 11.0.2.52
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
networks:
  hdspark_net:
    external: true
    name: hdspark_net 
